name: .NET CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted   # 👈 IMPORTANT (tumhara runner)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish -c Release -o publish

    # 🔥 Stop IIS Site
    - name: Stop IIS Site
      run: |
        Import-Module WebAdministration
        Stop-WebSite -Name "SalesDashboard"

    # 🔥 Clear old files
    - name: Clean IIS Folder
      run: |
        Remove-Item -Recurse -Force "C:\inetpub\wwwroot\SalesDashboard\*"

    # 🔥 Copy new files
    - name: Copy Files to IIS
      run: |
        Copy-Item -Path "publish\*" -Destination "C:\inetpub\wwwroot\SalesDashboard" -Recurse -Force

    # 🔥 Start IIS Site
    - name: Start IIS Site
      run: |
        Import-Module WebAdministration
        Start-WebSite -Name "SalesDashboard"
